apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: permissions-maintenance
  labels:
    name: permissions-maintenance
  namespace: apigee
spec:
  replicas: 1
  selector:
    matchLabels:
      component: permissions-maintenance
  template:
    metadata:
      labels:
        component: permissions-maintenance
        routable: "true"
      annotations:
        privateHosts: sso.k8s.local
        privatePaths: 3000:/permissions 3000:/resources-shared-with 3000:/permissions-heirs 3000:/permissions-heirs 3000:/users-who-can-access
    spec:
      containers:
      - name: permissions-maintenance
        image: permissions-maintenance
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "3000"
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: permissions
                key: pghost
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: permissions
                key: pguser
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: permissions
                key: pgpassword
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: permissions
                key: pgdatabase
          - name: SPEEDUP
            value: "10" 
          - name: INTERNAL_ROUTER
            value: "internal-router" 
          - name: IPADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
        ports:
          - containerPort: 3000